site_name: Test
#site_url: https://docs.chiyo-chan.me
markdown_extensions:
  - admonition
theme:
  name: 'readthedocs'
nav:
- Welcome: index.md
- Compute: compute.md
- Global infrastructure: globalinfrastructure.md
- How to use AWS: use.md
