site_name: The idiots guide on what AWS is
#site_url: ''
markdown_extensions:
  - admonition
theme:
  name: 'readthedocs'
nav:
- Welcome: index.md
- Compute: compute.md
- Global infrastructure: globalinfrastructure.md
- How to use AWS: use.md
- Networking: networking.md
- Storage: storage.md
- Databases: databases.md
- Security: security.md
- Compliance: compliance.md
- Monitoring: monitoring.md
- Pricing: pricing.md
#- Cloud Adoption: caf.md
#- Migration: migration.md
#- Innovate: innovate.md
#- Well-Architected Framework: framework.md

