site_name: The idiots guide on what AWS is
#site_url: https://docs.chiyo-chan.me
markdown_extensions:
  - admonition
theme:
  name: 'readthedocs'
nav:
- Welcome: index.md
- Compute: compute.md
- Global infrastructure: globalinfrastructure.md
- How to use AWS: use.md
- Networking: networking.md
- Storage: storage.md
